

create table if not exists users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY not null
        constraint users_pk
            primary key,
    name  varchar not null,
    email varchar unique not null
);

create table if not exists categories
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY not null
        constraint categories_pk
            primary key,
    name varchar unique not null
);

create table if not exists locations
(
    id  bigint GENERATED BY DEFAULT AS IDENTITY not null
        constraint locations_pk
            primary key,
    lat double precision not null,
    lon double precision not null
);

create table if not exists compilations
(
    id     bigint GENERATED BY DEFAULT AS IDENTITY not null
        constraint compilations_pk
            primary key,
    pinned boolean,
    title  varchar
);

create table if not exists events
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY not null
        constraint events_pk
            primary key,
    annotation         varchar   not null,
    category_id        bigint    not null
        constraint events_categories_id_fk
            references categories,
    confirmed_requests bigint,
    event_date         timestamp not null,
    initiator_id       bigint    not null
        constraint events_users_id_fk
            references users,
    paid               boolean   not null,
    title              varchar   not null,
    views              integer,
    created_on         timestamp,
    description        varchar,
    location_id        bigint    not null
        constraint events_locations_id_fk
            references locations,
    participant_limit  integer,
    published_on       timestamp,
    request_moderation boolean,
    state              varchar
);

create table if not exists compilation_events
(
    event_id       bigint
        constraint compilation_events_events_id_fk
            references events,
    compilation_id bigint
        constraint compilation_events_compilations_id_fk
            references compilations,
    primary key (event_id, compilation_id)
);

create table if not exists requests
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY not null
        constraint requests_pk
            primary key,
    created      timestamp,
    event_id     bigint
        constraint requests_events_id_fk
            references events,
    requester_id bigint
        constraint requests_users_id_fk
            references users,
    status        varchar
);
